spring:
  profiles:
    active: pro



---

server:
  port: 82
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: 123456789
  config:
    activate:
      on-profile: pro
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb1_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


---

server:
  port: 83
spring:
  config:
    activate:
      on-profile: dev